# Generated by Django 5.1.3 on 2024-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_emp_id', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=100)),
            ],
        ),
    ]
